version: '3.9'

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8870:8890"
    restart: unless-stopped
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 500M

networks:
  backend: