version: '3.9'

services:
  app:
    build:
      context: ./app
      dockerfile: ../../Dockerfile
    ports:
      - "8851:8890"
    restart: always
    networks:
      - backend
    depends_on:
      - zookeeper
      - broker
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 500M

  logs:
    build:
      context: ./log
      dockerfile: ../../Dockerfile
    ports:
      - "8852:8890"
    restart: always
    networks:
      - backend
    depends_on:
      - zookeeper
      - broker
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 500M

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    restart: always
    networks:
      - backend
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    restart: always
    ports:
      - "9092:9092"
    networks:
      - backend
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

networks:
  backend: