version: '3.9'

services:
  app:
    build:
      context: ./app
      dockerfile: ../../Dockerfile
    ports:
      - "8861:8890"
    restart: unless-stopped
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 500M

  logs:
    build:
      context: ./log
      dockerfile: ../../Dockerfile
    ports:
      - "8862:8890"
    restart: unless-stopped
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 500M

networks:
  backend: